version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: bionews-prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d' # Limita la retención a 7 días para ahorrar disco
    networks:
      - bionews-net
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: bionews-cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - bionews-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:10.0.0
    container_name: bionews-grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=CambiameBionews2026!
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - bionews-net
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  bionews-net:
    external: true
