import sqlite3
conn = sqlite3.connect('data/data.db')
cursor = conn.cursor()
cursor.execute("PRAGMA table_info(pertinencias)")
print("Pertinencias:", cursor.fetchall())
cursor.execute("SELECT * FROM pertinencias LIMIT 1")
print("Pertinencia row:", cursor.fetchone())
cursor.execute("PRAGMA table_info(user_category_views)")
print("user_category_views:", cursor.fetchall())
cursor.execute("SELECT * FROM user_category_views LIMIT 5")
print("user_category_views rows:", cursor.fetchall())
conn.close()
